[package]
name = "ic-http-auth"
description = "Canister side support for ICP HTTP authentication"
readme = "README.md"
documentation = "https://docs.rs/ic-http-auth"
categories = ["api-bindings", "algorithms", "cryptography::cryptocurrencies"]
keywords = ["internet-computer", "icp", "dfinity", "http", "authentication"]
include = ["src", "Cargo.toml", "README.md"]

version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
ic-http-certification.workspace = true
ic-canister-sig-creation.workspace = true
ic-signature-verification.workspace = true
candid.workspace = true
thiserror.workspace = true
base64.workspace = true
serde.workspace = true
serde_json.workspace = true
nom.workspace = true
sha2.workspace = true
p256.workspace = true

canbench-rs = { version = "0.1.12", optional = true }
ic-cdk = { workspace = true, optional = true }
hex = { workspace = true, optional = true }

[features]
canbench-rs = ["dep:ic-cdk", "dep:canbench-rs", "dep:hex"]
